# Generated by Django 6.0.3 on 2026-05-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='availability_id',
            new_name='availability',
        ),
    ]
