# Generated by Django 6.0.3 on 2026-05-16 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_availability_id_appointment_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.availability'),
        ),
    ]
