# Generated by Django 6.0.3 on 2026-03-12 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_availability_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='user',
        ),
        migrations.AddField(
            model_name='availability',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.provider'),
        ),
    ]
